stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: pipeline:${CICD_GIT_COMMIT}
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deploy/singleshot.yml
  when:
    branch:
      include:
      - master
timeout: 60
branch: {}
