---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: pipeline-${CICD_GIT_COMMIT}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pipeline-${CICD_GIT_COMMIT}
  template:
    metadata:
      labels:
        app: pipeline-${CICD_GIT_COMMIT}
      name: pipeline-${CICD_GIT_COMMIT}
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - image: ${CICD_IMAGE}:${CICD_GIT_COMMIT}
        name: pipeline
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pipeline-${CICD_GIT_COMMIT}
spec:
  rules:
  - host: pipelines-${CICD_GIT_COMMIT}.demo.rnchr.nl
    http:
      paths:
      - backend:
          serviceName: pipeline-${CICD_GIT_COMMIT}
          servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
      app: pipeline
      version: "${CICD_GIT_COMMIT}"
  name: pipeline-${CICD_GIT_COMMIT}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  type: ClusterIP
  selector:
    app: pipeline-${CICD_GIT_COMMIT}
